version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 5

  - package-ecosystem: "cargo"
    directory: "/contracts"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 5
